layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 8
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
    - AcaTool_Resource_NewsreportSearch
    - iOS_Project_JSONMes
    - iOS_Project_TodoList180704
    
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
   twitter: TonyTang_here
  # unsplash: your_username
  # vk: your_username
   website: http://tonytangzixuan.com
  # youtube: your_username

topics:
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png

#  - name: Web design

#  - name: Sass
#    web_url: https://github.com/topics/sass
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
